### ISSUE TITLE
Quotes don't show up right after running FFXIV

### ISSUE THREAD

**Issue by Nillinn** [Soreepeong/QuoteOfTheLobby#1]
The sentences don't show up on the first time I see the title screen, right after running the game. They're only appearing when I go back to the title screen manually, from the log in screen.
I do use  the Title Edit plugin, though. Could it be some kind of incompatibility?

I love the plugin btw. Did you get the idea from that fighting game with the random quotes every time you start a round? I forgot its name lol

**Comment by Soreepeong** [comment]
How long does it take until the game freezes momentarily(when Dalamud loads) after launching the game? As the plugin figures out whether it's on title screen by capturing the moment it becomes visible or hidden, if Dalamud loads when title menu is already showing, the plugin does not know if title screen is already visible. Regardless, it needs to be fixed, though. For a quick workaround, I'll add LoadOrder or something to plugin definition json file.

The idea isn't much - I like Orbonne quotes, and then figured out title menu is the best place to place random quotes.

And then you get powerpoint shitpost tier random quote combinations.

![Heehee HAHA hahaha HEEHEE haha HEEEEEE!!! The louder they are, the quieter it is when they fall.](https://pbs.twimg.com/media/FFIynk2akAA6-BN?format=png&name=large)

**Comment by Nillinn** [comment]
It freezes for about 2-3 seconds before loading the title screen

**Comment by Soreepeong** [comment]
IT should be fixed now.
