### ISSUE TITLE
[Feature Request]: Show source of dialogue 

### ISSUE THREAD

**Issue by linus-cheng-xw** [Soreepeong/QuoteOfTheLobby#3]
Hello Soreepeong,

Thank you so much for this plugin; my friends and I love sharing the random dialogues we get when we log in. However, it drives us insane to see a dialogue we recognize from somewhere, but we just can't remember where it's from. Would it be possible to show the name of the NPC, or the source of the dialogue?

Kind Regards,
Linus

**Comment by Soreepeong** [comment]
As far as I know, the data file installed with the game does not provide information on which quote is from which NPC, so it would be impossible for now.

**Comment by linus-cheng-xw** [comment]
Damn thats a shame. Thank you, I still enjoy your plugin everyday regardless <3
